remote_theme: SteveZMTstudios/jekyll-mdui-theme
plugins:
  - jekyll-remote-theme
title: Phigros 历史版本收集
description: 可能是最全的 Phigros 旧版本收集 - Phigros History。收录了自 1.0.0 版本以来的绝大多数 Phigros 版本。
lang: zh-CN
show_downloads: false
google_analytics: G-STRYCQ7E8X
beian: 浙ICP备2025213066号-1
url: "https://stevezmt.top"
baseurl: "Phigros-history/" # 用户主页仓库留空；项目仓库填 "/<repo>"

